### ISSUE TITLE
Fix copy citation button

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/web#162]

**Comment by StevenClontz** [comment]
In addition to the fix at #164, we have another issue. When visiting https://topology.pi-base.org/spaces one can edit the search parameters, and it appears to update the citation for that page. However, those updates aren't reflected in the copied text from the Markdown button. We should fix this.

**Comment by StevenClontz** [comment]
I believe https://github.com/pi-base/web/pull/157 has a hint on what we might need to do (use `#key` to force the component to rerender given new values for the text to be copied).

**Comment by prabau** [comment]
Has #164 done anything?  It used to be that the `Copy: Markdown link` button on the Explore page would copy something that would display the current search.  But that behavior became broken at some point.  And that it still broken, even with #164.  What we get is just:

`[π-Base, Explore](https://topology.pi-base.org/spaces)`

**Comment by StevenClontz** [comment]
I think it fixed the front page button, but there's still work to do on the explore page.

**Comment by StevenClontz** [comment]
Closed by #170
